name: Deploy to Development

on:
  push:
    branches:
      - main

jobs:
  setup-fluxcd:
    name: Setup FluxCD for Development Environment
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install FluxCD CLI
      run: |
        curl -s https://toolkit.fluxcd.io/install.sh | sudo bash

    - name: Bootstrap FluxCD in the Development Cluster
      run: |
        flux bootstrap github \
          --owner=${{ github.repository_owner }} \
          --repository=${{ github.event.repository.name }} \
          --branch=main \
          --path=./clusters/dev \
          --personal

  deploy-app:
    name: Deploy Application to Development
    needs: setup-fluxcd
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update Helm Chart in FluxCD Configuration
      run: |
        # Assuming the use of Kustomize with FluxCD
        # Update the HelmRelease manifest to point to the new version of your app
        # This example assumes a simple update to a HelmRelease file
        # You might need to customize this step based on your application's versioning strategy
        NEW_IMAGE_TAG=$(git rev-parse --short HEAD)
        yq e ".spec.values.image.tag = \"$NEW_IMAGE_TAG\"" -i ./clusters/dev/myapp-release.yaml
        
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add ./clusters/dev/myapp-release.yaml
        git commit -m "Update development image tag to $NEW_IMAGE_TAG"
        git push

    - name: Ensure FluxCD Syncs the Changes
      run: |
        flux reconcile source git flux-system
