name: Deploy to Staging

on:
  push:
    branches:
      - main
    paths:
      - 'charts/myapp/**'
      - 'k8s/staging/**'

jobs:
  deploy-app-staging:
    name: Deploy Application to Staging
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure Git for FluxCD Updates
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Update HelmRelease for Staging
      run: |
        # Assuming HelmRelease files are managed under k8s/staging for staging environment
        # Update the HelmRelease manifest to point to the new version of your app
        # Here we use the git commit SHA as the image tag for simplicity
        NEW_IMAGE_TAG=$(git rev-parse --short HEAD)
        yq e ".spec.chart.spec.values.image.tag = \"$NEW_IMAGE_TAG\"" -i ./k8s/staging/myapp-helmrelease.yaml
        
        # Check if there are changes. If so, commit and push them.
        if [ -n "$(git status --porcelain)" ]; then
          git add ./k8s/staging/myapp-helmrelease.yaml
          git commit -m "Update staging image tag to $NEW_IMAGE_TAG"
          git push
        else
          echo "No changes in HelmRelease. Skipping commit."
        fi

    - name: Ensure FluxCD Syncs the Changes in Staging
      run: |
        flux reconcile source git flux-system --k8s-namespace=flux-staging
