name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag to deploy'
        required: true

jobs:
  ask-for-approval:
    runs-on: ubuntu-latest
    steps:
    - name: Manual Approval
      uses: actions/github-script@v3
      with:
        script: |
          const { issue: { number: issueNumber }, repo: { owner, repo } } = context
          github.issues.createComment({
            owner,
            repo,
            issue_number: issueNumber,
            body: 'Deployment to production is pending approval. @team-lead, please review and approve.',
          })
        github.actions.addReviewers({
          owner,
          repo,
          pull_number: issueNumber,
          reviewers: ['team-lead']
        })
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-to-prod:
    needs: ask-for-approval
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure Git for FluxCD Updates
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Update HelmRelease for Production
      run: |
        NEW_IMAGE_TAG=${{ github.event.inputs.tag }}
        yq e ".spec.chart.spec.values.image.tag = \"$NEW_IMAGE_TAG\"" -i ./k8s/prod/myapp-helmrelease.yaml
        
        git add ./k8s/prod/myapp-helmrelease.yaml
        git commit -m "Deploy image tag $NEW_IMAGE_TAG to production"
        git push

    - name: Ensure FluxCD Syncs the Changes in Production
      run: flux reconcile source git flux-system --k8s-namespace=flux-prod
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
