name: 'Kubernetes Deploy'
description: 'Deploys applications to Kubernetes using Helm.'
inputs:
  kubeconfig-data:
    description: 'Base64-encoded kubeconfig data for Kubernetes cluster access.'
    required: true
  chart-path:
    description: 'Path to the Helm chart directory.'
    required: true
  release-name:
    description: 'Helm release name.'
    required: true
  namespace:
    description: 'Kubernetes namespace for the deployment.'
    required: true
  values-file:
    description: 'Path to the values file to use with Helm.'
    required: false
    default: 'values.yaml'
  extra-args:
    description: 'Extra arguments to pass to the Helm upgrade command.'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Decode kubeconfig data
      run: echo "${{ inputs.kubeconfig-data }}" | base64 -d > ./kubeconfig
      shell: bash

    - name: Set KUBECONFIG environment variable
      run: echo "KUBECONFIG=$(pwd)/kubeconfig" >> $GITHUB_ENV
      shell: bash

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      shell: bash

    - name: Add Helm repos or other setup here
      run: |
        # Placeholder for additional Helm setup commands, such as helm repo add
      shell: bash

    - name: Deploy with Helm
      run: |
        helm upgrade --install ${{ inputs.release-name }} ${{ inputs.chart-path }} \
          --namespace ${{ inputs.namespace }} \
          -f ${{ inputs.values-file }} \
          ${{ inputs.extra-args }}
      shell: bash
