name: 'Setup Environment'
description: 'Sets up the Rust toolchain, configures environment variables, and caches dependencies for faster builds.'

inputs:
  rust-version:
    description: 'Version of the Rust toolchain to use.'
    required: false
    default: 'stable'
  cache-key-prefix:
    description: 'Prefix for the cache key, unique to the job.'
    required: false
  additional-env-vars:
    description: 'JSON string of additional environment variables to set.'
    required: false

outputs:
  rust-path:
    description: 'The path to the Rust toolchain installation.'

runs:
  using: 'composite'
  steps:
  
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ inputs.rust-version }}
        profile: minimal
        override: true
        components: rustfmt, clippy

    - name: Validate Inputs
      shell: bash
      run: |
        if ! [[ "${{ inputs.rust-version }}" =~ ^(1\.[0-9]+|stable|beta|nightly)$ ]]; then
          echo "Error: 'rust-version' input is invalid."
          exit 1
        fi

    - name: Set up additional environment variables
      shell: bash
      run: |
        if [ -n "${{ inputs.additional-env-vars }}" ]; then
          # Assuming the additional-env-vars input is a JSON string of key-value pairs
          echo "Setting additional environment variables..."
          echo "${{ inputs.additional-env-vars }}" | jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' >> $GITHUB_ENV
        fi
        
    - name: Cache Cargo registry
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ inputs.cache-key-prefix }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ inputs.cache-key-prefix }}-cargo-registry-

    - name: Cache Cargo target
      uses: actions/cache@v2
      with:
        path: target
        key: ${{ inputs.cache-key-prefix }}-cargo-target-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ inputs.cache-key-prefix }}-cargo-target-

    - name: Cache Cargo index
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/git/db
          ~/.cargo/registry/index
        key: ${{ inputs.cache-key-prefix }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ inputs.cache-key-prefix }}-cargo-index-

    - name: Output Toolchain Details
      shell: bash
      run: |
        echo "Rust version: $(rustc --version)"
        echo "Cargo version: $(cargo --version)"
        echo "rustfmt version: $(rustfmt --version)"
        echo "clippy version: $(cargo clippy -- --version)"
        echo "rust-path=$(which rustc)" >> $GITHUB_ENV
