name: "SonarCloud Analysis"
description: "Performs SonarCloud analysis on projects."
inputs:
  sonar-token:
    description: "SonarCloud authentication token."
    required: true
  organization:
    description: "SonarCloud organization key."
    required: true
  project-key:
    description: "SonarCloud project key."
    required: true
  project-name:
    description: "SonarCloud project name."
    required: true
  project-version:
    description: "Project version."
    default: "1.0.0"
    required: false
  sources:
    description: "Source files for SonarCloud to analyze."
    default: "."
    required: false
  tests:
    description: "Test files for SonarCloud to analyze."
    default: "."
    required: false
  exclusions:
    description: "Files and directories to exclude from analysis."
    default: ""
    required: false
  test-inclusions:
    description: "Test files to include in analysis."
    default: ""
    required: false
  allow-failure:
    description: "Specifies whether the action should allow failure."
    default: "false"
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SonarCloud scanner
      uses: sonarsource/sonarcloud-github-action@master
      env:
        SONAR_TOKEN: ${{ inputs.sonar-token }}
      with:
        args: >
          -Dsonar.projectKey=${{ inputs.project-key }}
          -Dsonar.organization=${{ inputs.organization }}
          -Dsonar.projectName=${{ inputs.project-name }}
          -Dsonar.projectVersion=${{ inputs.project-version }}
          -Dsonar.sources=${{ inputs.sources }}
          -Dsonar.tests=${{ inputs.tests }}
          -Dsonar.exclusions=${{ inputs.exclusions }}
          -Dsonar.test.inclusions=${{ inputs.test-inclusions }}
