apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: app-virtualservice-canary
spec:
  hosts:
    - "{{ .Values.app.host }}"
  gateways:
    - "{{ .Values.gateway.name }}"
  http:
    - route:
        - destination:
            host: "{{ .Values.app.host }}"
            subset: stable
          weight: {{ .Values.canary.weight.stable }}
        - destination:
            host: "{{ .Values.app.host }}"
            subset: canary
          weight: {{ .Values.canary.weight.canary }}
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: app-destinationrule-canary
spec:
  host: "{{ .Values.app.host }}"
  subsets:
    - name: stable
      labels:
        version: stable
    - name: canary
      labels:
        version: canary
