apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base resources include common configurations across all deployment strategies
resources:
  - ../../base

# Canary-specific resources and patches
resources:
  - canary.yaml  # This file includes both VirtualService and DestinationRule configurations

patchesStrategicMerge:
  - destinationrule-canary.yaml  # If you have specific tweaks or overrides for the canary DestinationRule

# ConfigMap generation for canary-specific configurations
configMapGenerator:
  - name: canary-config
    behavior: merge
    literals:
      - "mode=canary"
      - "percentage=20"  # Example: Define the percentage of traffic directed to the canary version

# Secret generation for sensitive data specific to the canary deployment
# secretGenerator:
#   - name: canary-secrets
#     files:
#       - secrets/canary.env

# Custom images for the canary deployment
images:
  - name: app-image
    newName: registry.example.com/app
    newTag: "canary"  # Use the tag that corresponds to the canary version of your app

# Annotations and labels specific to canary deployments
commonLabels:
  deployment: canary

commonAnnotations:
  "strategy.rollout.tactic": "canary"
