name: 'Code Security Scan'
description: 'Performs code security analysis using CodeQL and Rust linting tools.'
inputs:
  setup-codeql-config:
    description: 'Configuration steps for CodeQL setup.'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: 'rust'
        # This allows for custom configuration of the CodeQL setup.
        config-file: ${{ inputs.setup-codeql-config }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

    - name: Install Rust Linting Tools
      run: rustup component add clippy rustfmt
      shell: bash

    - name: Run Clippy (Rust Linter)
      run: cargo clippy -- -D warnings
      shell: bash

    - name: Check Code Formatting with Rustfmt
      run: cargo fmt -- --check
      shell: bash
