apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}               # The application name, parameterized
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.replicaCount }}        # The number of replicas, parameterized
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" # Parameterized image repository and tag
        ports:
        - containerPort: {{ .Values.app.port }}                        # The application port, parameterized
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}                  # CPU resource requests, parameterized
            memory: {{ .Values.resources.requests.memory }}            # Memory resource requests, parameterized
          limits:
            cpu: {{ .Values.resources.limits.cpu }}                    # CPU resource limits, parameterized
            memory: {{ .Values.resources.limits.memory }}              # Memory resource limits, parameterized
        env:                                                         # Environment variables
        - name: ENVIRONMENT
          value: {{ .Values.environment }}                            # Environment type, parameterized
        # Add other environment variables, secrets, or config maps as needed
      # Add additional containers, such as sidecars or init containers if needed
