apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Values.app.name }}-destination-rule
spec:
  host: {{ .Values.app.host }}               # The service host, parameterized
  trafficPolicy:
    loadBalancer:
      simple: {{ .Values.loadBalancer.type }} # Load balancer type, parameterized (e.g., ROUND_ROBIN)
    connectionPool:
      tcp:
        maxConnections: {{ .Values.connectionPool.tcp.maxConnections }}  # Max TCP connections, parameterized
      http:
        http1MaxPendingRequests: {{ .Values.connectionPool.http.http1MaxPendingRequests }}  # Max pending HTTP requests, parameterized
        maxRequestsPerConnection: {{ .Values.connectionPool.http.maxRequestsPerConnection }} # Max requests per connection, parameterized
    outlierDetection:
      consecutiveGatewayErrors: {{ .Values.outlierDetection.consecutiveGatewayErrors }} # Num. of gateway errors before ejection, parameterized
      interval: {{ .Values.outlierDetection.interval }}                               # Interval between checks, parameterized
      baseEjectionTime: {{ .Values.outlierDetection.baseEjectionTime }}               # Base ejection time, parameterized
      maxEjectionPercent: {{ .Values.outlierDetection.maxEjectionPercent }}           # Max ejection percentage, parameterized
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
