apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: app-destinationrule-bluegreen
spec:
  host: "{{ .Values.app.serviceHost }}"
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
    - name: blue
      labels:
        version: blue
    - name: green
      labels:
        version: green
