apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base resources include common configurations across blue and green deployments
resources:
  - ../../base

# Common labels for all resources managed by this kustomization
commonLabels:
  app: app-name
  strategy: blue-green

# Define configurations specific to the blue environment
bases:
  - name: blue
    resources:
      - blue.yaml
    patchesStrategicMerge:
      - patch-blue.yaml

# Define configurations specific to the green environment
bases:
  - name: green
    resources:
      - green.yaml
    patchesStrategicMerge:
      - patch-green.yaml

# ConfigMap generation for environment-specific configurations
configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
      - "env=blue"  # or "env=green" based on the active deployment phase

# Secret generation for sensitive data, ensuring they are managed securely
# secretGenerator:
#   - name: app-secret
#     literals:
#       - secretKey=secretValue

# Custom images, dynamically pointing to the correct version for blue or green deployment
images:
  - name: app-image
    newName: registry.example.com/app
    newTag: "blue-latest"  # or "green-latest" based on the active deployment phase

# Additional customization for the blue-green strategy
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: app-deployment-blue
    path: deployment-blue-patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: app-deployment-green
    path: deployment-green-patch.yaml
