apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Resources to customize
resources:
  - ../../base

# Namespace to deploy the resources into (specific to the dev environment)
namespace: development

# Common labels to add to all the resources
commonLabels:
  env: development

# Patches to apply to the base resources
patchesStrategicMerge:
  - patch-deployment-dev.yaml
  - patch-service-dev.yaml
  - virtualservice-dev.yaml
  - destinationrule-dev.yaml

# ConfigMap generator with files specific to the development environment
configMapGenerator:
  - name: app-config
    behavior: merge
    files:
      - dev-config.properties

# Secret generator if you have any secrets specific to the development environment
# secretGenerator:
#   - name: app-secret
#     files:
#       - secret.properties
#     type: Opaque

# Image transformer to use images specific to the development environment
images:
  - name: app-image
    newName: dev-registry.example.com/app
    newTag: "dev-latest"

# Optionally, you can specify patches for specific resources, for example:
# patchesJson6902:
# - target:
#     group: apps
#     version: v1
#     kind: Deployment
#     name: app-deployment
#   path: patch-deployment-dev.json
