apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base resources to customize for A/B testing
resources:
  - ../../base

# A/B testing specific patches to apply
patchesStrategicMerge:
  - abtest.yaml  # Applying A/B testing rules
  - destinationrule-abtest.yaml  # Defining subsets for versions

# Customizations for the A/B testing environment
configMapGenerator:
  - name: abtest-config
    literals:
      - "experiment=abtest"

# Custom images if necessary for the test versions
images:
  - name: app-image
    newName: registry.example.com/app
    newTag: "abtest-version"

# Labels to add for resources involved in A/B testing
commonLabels:
  strategy: ab-testing

# Annotations to add specific metadata for A/B testing
commonAnnotations:
  "abtest.strategy/version": "v1"
  "abtest.strategy/weight": "50%"
