name: 'Dependency Vulnerability Scan'
description: 'Scans Rust project dependencies for known vulnerabilities using cargo-audit.'
inputs:
  audit-flags:
    description: 'Additional flags for cargo-audit command.'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install cargo-audit
      run: cargo install cargo-audit
      shell: bash

    - name: Scan dependencies for vulnerabilities
      run: cargo audit ${{ inputs.audit-flags }}
      shell: bash
