name: 'Docker Build and Push to Minikube'
description: 'Builds a Docker image and pushes it to the Minikube Docker registry.'

inputs:
  dockerfile:
    description: 'Path to the Dockerfile.'
    required: true
  context:
    description: 'Path to the build context.'
    required: true
    default: '.'
  image-name:
    description: 'Name of the Docker image to build.'
    required: true
  image-tag:
    description: 'Tag for the Docker image.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Minikube Docker environment
      run: |
        minikube -p minikube docker-env --shell bash >> "$GITHUB_ENV"
      shell: bash

    - name: Build Docker image
      run: |
        source "$GITHUB_ENV"
        docker build -f ${{ inputs.dockerfile }} -t minikube-local-registry:5000/${{ inputs.image-name }}:${{ inputs.image-tag }} ${{ inputs.context }}
      shell: bash

    - name: Push Docker image to Minikube registry
      run: |
        source "$GITHUB_ENV"
        docker push minikube-local-registry:5000/${{ inputs.image-name }}:${{ inputs.image-tag }}
      shell: bash
